spring:
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:PLAINTEXT_HOST://localhost:9091}
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    password: test

  #  datasource:
  #    username: postgres
  #    password: postgres
  #    url: jdbc:postgresql://localhost:5432/goods-warehouse
  jpa:
    hibernate:
      ddl-auto: validate